sudo: required

env:
  global:
    - BINARY_FILE_NAME=ecs_agent_version_checker
    - DOCKER_IMAGE_TAG=parabolic/ecs_agent_version_checker

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker build -t $DOCKER_IMAGE_TAG .
  - docker run -v `pwd`:/project $DOCKER_IMAGE_TAG /bin/sh -c "cd /project && mkdir -p bin && CGO_ENABLED=0 GOOS=linux go build -o ./bin/$BINARY_FILE_NAME ./src/main.go"

script:
  - ls -lat
  - echo "Good to go"
